### ISSUE TITLE
How to get a non inline toml string from a document

### ISSUE THREAD

**Issue by HUD-Software** [SamboyCoding/Tomlet#29]
Considering the following toml file:
```toml
[package]
authors = [ "me", "I", "myself" ]
name = "proj"
version = "0.0.1"

[profile]

```

After loading and saving it with the following code (tomlet 5.1.3):
```C#
TomlDocument document = TomlParser.ParseFile("file.toml");
using StreamWriter streamWriter= new("result.toml");
document.ForceNoInline = true; // With or withou this, the result is the same
streamWriter.Write(document.SerializedValue);
```
The content of `result.toml` file is inlined:
```toml
package = { authors = [ "me", "I", "myself", ], name = "proj", version = "0.0.1" }
profile = {  }
```
How can we get a non inlined string for a document that is loaded not inlined?
